# Generated by Django 5.1.4 on 2026-06-01 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('owner_login', models.CharField(max_length=120)),
                ('owner_avatar_url', models.URLField(blank=True)),
                ('html_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('homepage', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, max_length=60)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('stargazers_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('open_issues_count', models.IntegerField(default=0)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.repo'),
        ),
    ]
