# Generated by Django 5.1.4 on 2026-06-11 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_repo_post_repo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(unique=True)),
                ('login', models.CharField(max_length=120)),
                ('avatar_url', models.URLField(blank=True)),
                ('access_token', models.CharField(max_length=255)),
                ('scopes', models.CharField(blank=True, max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
