# Generated by Django 5.1.4 on 2026-06-17 10:03

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_githubaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubaccount',
            name='access_token',
            field=core.fields.EncryptedCharField(max_length=500),
        ),
    ]
