# Generated by Django 5.1.4 on 2026-06-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='source',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['-stargazers_count'], name='core_repo_stargaz_cd084f_idx'),
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['name'], name='core_repo_name_8464ff_idx'),
        ),
    ]
